#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION="0.0.5"

svn commit -m ""
cd /tmp
svn co file:///home/keithhedger/Development/SVN/GtkSu
find GtkSu -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/GtkSu/makepkg
tar -czvf GtkSu-${VERSION}.tar.gz GtkSu
rm -r /tmp/GtkSu